# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class TaskLineReaderServiceModel(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        TaskLineReaderServiceModel - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id_app_project': 'int',
            'id_task_line': 'int',
            'inputs': 'list[str]',
            'tasks': 'list[TaskReaderServiceModel]'
        }

        self.attribute_map = {
            'id_app_project': 'IdAppProject',
            'id_task_line': 'IdTaskLine',
            'inputs': 'Inputs',
            'tasks': 'Tasks'
        }

        self._id_app_project = None
        self._id_task_line = None
        self._inputs = None
        self._tasks = None

    @property
    def id_app_project(self):
        """
        Gets the id_app_project of this TaskLineReaderServiceModel.


        :return: The id_app_project of this TaskLineReaderServiceModel.
        :rtype: int
        """
        return self._id_app_project

    @id_app_project.setter
    def id_app_project(self, id_app_project):
        """
        Sets the id_app_project of this TaskLineReaderServiceModel.


        :param id_app_project: The id_app_project of this TaskLineReaderServiceModel.
        :type: int
        """
        self._id_app_project = id_app_project

    @property
    def id_task_line(self):
        """
        Gets the id_task_line of this TaskLineReaderServiceModel.


        :return: The id_task_line of this TaskLineReaderServiceModel.
        :rtype: int
        """
        return self._id_task_line

    @id_task_line.setter
    def id_task_line(self, id_task_line):
        """
        Sets the id_task_line of this TaskLineReaderServiceModel.


        :param id_task_line: The id_task_line of this TaskLineReaderServiceModel.
        :type: int
        """
        self._id_task_line = id_task_line

    @property
    def inputs(self):
        """
        Gets the inputs of this TaskLineReaderServiceModel.


        :return: The inputs of this TaskLineReaderServiceModel.
        :rtype: list[str]
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """
        Sets the inputs of this TaskLineReaderServiceModel.


        :param inputs: The inputs of this TaskLineReaderServiceModel.
        :type: list[str]
        """
        self._inputs = inputs

    @property
    def tasks(self):
        """
        Gets the tasks of this TaskLineReaderServiceModel.


        :return: The tasks of this TaskLineReaderServiceModel.
        :rtype: list[TaskReaderServiceModel]
        """
        return self._tasks

    @tasks.setter
    def tasks(self, tasks):
        """
        Sets the tasks of this TaskLineReaderServiceModel.


        :param tasks: The tasks of this TaskLineReaderServiceModel.
        :type: list[TaskReaderServiceModel]
        """
        self._tasks = tasks

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

